### ISSUE TITLE
Exception in plugin DocHub 2.2.2-beta

### ISSUE THREAD

**Issue by mshogin** [RabotaRu/DocHub#197]
java.lang.StackOverflowError
	at com.intellij.util.containers.hash.HashUtil.hash(HashUtil.java:24)
	at com.intellij.util.containers.hash.LinkedHashMap.get(LinkedHashMap.java:74)
	at com.intellij.util.containers.SLRUMap.get(SLRUMap.java:80)
	at com.intellij.util.containers.SLRUCache.get(SLRUCache.java:42)
	at com.intellij.util.indexing.impl.MapIndexStorage.lambda$read$1(MapIndexStorage.java:271)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:233)
	at com.intellij.util.indexing.impl.MapIndexStorage.read(MapIndexStorage.java:269)
	at com.intellij.util.indexing.impl.MapIndexStorage.read(MapIndexStorage.java:23)
	at com.intellij.util.indexing.impl.storage.TransientChangesIndexStorage.read(TransientChangesIndexStorage.java:191)
	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java:240)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.getNullableIndexedData(MapReduceIndexBase.java:79)
	at com.intellij.util.indexing.impl.storage.TransientFileContentIndex.getNullableIndexedData(TransientFileContentIndex.java:99)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.lambda$getIndexedFileData$1(MapReduceIndexBase.java:61)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:233)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.getIndexedFileData(MapReduceIndexBase.java:59)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.getIndexedFileData(CompositeInvertedIndexBase.java:149)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$getFileData$3(FileBasedIndexEx.java:220)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processExceptions$7(FileBasedIndexEx.java:330)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:233)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processExceptions$8(FileBasedIndexEx.java:330)
	at com.intellij.util.indexing.diagnostic.IndexAccessValidator.validate(IndexAccessValidator.java:46)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:328)
	at com.intellij.util.indexing.FileBasedIndexEx.getFileData(FileBasedIndexEx.java:213)
	at com.intellij.util.indexing.FileBasedIndexImpl.getFileData(FileBasedIndexImpl.java:1089)
	at org.dochub.idea.arch.indexing.CacheBuilder.parseYamlManifest(CacheBuilder.java:84)
	at org.dochub.idea.arch.indexing.CacheBuilder.parseYamlManifest(CacheBuilder.java:95)
	at org.dochub.idea.arch.indexing.CacheBuilder.parseYamlManifest(CacheBuilder.java:95)
        ..................................................................

**Comment by rpiontik** [comment]
Исправлено в 2.2.5
