### ISSUE TITLE
Ошибка при сборке контейнера для v3.5.0

### ISSUE THREAD

**Issue by khaale** [RabotaRu/DocHub#428]
При попытке сборки
```
~/Documents/projects/DocHub ((v3.5.0))
$ docker-compose up --build
```
выдается ошибка:

```
#0 77.14  error  in ./plugins/charts/components/bar/BarChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/bar'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/bar/BarChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/bar'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/bubble/BubbleChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/bubble'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/bubble/BubbleChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/bubble'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/doughnut/DoughnutChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/doughnut'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/doughnut/DoughnutChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/doughnut'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/line/LineChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/line'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/line/LineChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/line'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/pie/PieChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/pie'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/pie/PieChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/pie'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/polararea/PolarArea.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/polararea'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/polararea/PolarArea.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/polararea'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/polararea/PolarArea.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'chartjs-color' in '/var/www/plugins/charts/components/polararea'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/radar/RadarChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/radar'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/radar/RadarChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/radar'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/radar/RadarChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'chartjs-color' in '/var/www/plugins/charts/components/radar'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/scatter/ScatterChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/scatter'
#0 77.14
#0 77.14  error  in ./plugins/charts/components/scatter/ScatterChart.vue?vue&type=script&lang=js&
#0 77.14
#0 77.14 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/scatter'
#0 77.14
#0 77.14  ERROR  Error: Build failed with errors.
#0 77.14 Error: Build failed with errors.
#0 77.14     at /var/www/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
#0 77.14     at /var/www/node_modules/webpack/lib/webpack.js:148:8
#0 77.14     at /var/www/node_modules/webpack/lib/HookWebpackError.js:68:3
#0 77.14     at Hook.eval [as callAsync] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
#0 77.14     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/node_modules/tapable/lib/Hook.js:18:14)
#0 77.14     at Cache.shutdown (/var/www/node_modules/webpack/lib/Cache.js:150:23)
#0 77.14     at /var/www/node_modules/webpack/lib/Compiler.js:1228:15
#0 77.14     at Hook.eval [as callAsync] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
#0 77.14     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/node_modules/tapable/lib/Hook.js:18:14)
#0 77.14     at Compiler.close (/var/www/node_modules/webpack/lib/Compiler.js:1221:23)
#0 77.14     at /var/www/node_modules/webpack/lib/webpack.js:147:16
#0 77.14     at finalCallback (/var/www/node_modules/webpack/lib/Compiler.js:441:32)
#0 77.14     at /var/www/node_modules/webpack/lib/Compiler.js:458:13
#0 77.14     at Hook.eval [as callAsync] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
#0 77.14     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/node_modules/tapable/lib/Hook.js:18:14)
#0 77.14     at onCompiled (/var/www/node_modules/webpack/lib/Compiler.js:456:21)
#0 77.14     at /var/www/node_modules/webpack/lib/Compiler.js:1199:17
#0 77.14     at Hook.eval [as callAsync] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
#0 77.14     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/node_modules/tapable/lib/Hook.js:18:14)
#0 77.14     at /var/www/node_modules/webpack/lib/Compiler.js:1195:33
#0 77.14     at finalCallback (/var/www/node_modules/webpack/lib/Compilation.js:2789:11)
#0 77.14     at /var/www/node_modules/webpack/lib/Compilation.js:3094:11
#0 77.14     at Hook.eval [as callAsync] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
#0 77.14     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/node_modules/tapable/lib/Hook.js:18:14)
#0 77.14     at /var/www/node_modules/webpack/lib/Compilation.js:3087:38
#0 77.14     at eval (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
#0 77.14     at eval (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
#0 77.14     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#0 77.25 npm notice
#0 77.25 npm notice New minor version of npm available! 10.1.0 -> 10.2.3
#0 77.25 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.3>
#0 77.25 npm notice Run `npm install -g npm@10.2.3` to update!
#0 77.25 npm notice
```

**Comment by Saamuel** [comment]
не нашли решение?

**Comment by khaale** [comment]
> не нашли решение?

Нет, пока переключился на версию 3.4.0

**Comment by rpiontik** [comment]
Исправлено v3.6.0
