### ISSUE TITLE
Ошибка при docker compose up

### ISSUE THREAD

**Issue by Saamuel** [RabotaRu/DocHub#429]
Не запускается сборка

```
 => ERROR [nginx builder 5/5] RUN npm run build                                                                                                    139.0s
------
 > [nginx builder 5/5] RUN npm run build:
1.468
1.468 > dochubcore@1.0.6 build
1.468 > vue-cli-service build
1.468
2.809 Browserslist: caniuse-lite is outdated. Please run:
2.809   npx update-browserslist-db@latest
2.809   Why you should do it regularly: https://github.com/browserslist/update-db#readme
2.906 All browser targets in the browserslist configuration have supported ES module.
2.906 Therefore we don't build two separate bundles for differential loading.
2.906
2.942
2.944 -  Building for production...
7.230 Browserslist: caniuse-lite is outdated. Please run:
7.230   npx update-browserslist-db@latest
7.230   Why you should do it regularly: https://github.com/browserslist/update-db#readme
7.243 Browserslist: caniuse-lite is outdated. Please run:
7.243   npx update-browserslist-db@latest
7.243   Why you should do it regularly: https://github.com/browserslist/update-db#readme
7.243 Browserslist: caniuse-lite is outdated. Please run:
7.243   npx update-browserslist-db@latest
7.243   Why you should do it regularly: https://github.com/browserslist/update-db#readme
124.6 Browserslist: caniuse-lite is outdated. Please run:
124.6   npx update-browserslist-db@latest
124.6   Why you should do it regularly: https://github.com/browserslist/update-db#readme
124.6 Browserslist: caniuse-lite is outdated. Please run:
124.6   npx update-browserslist-db@latest
124.6   Why you should do it regularly: https://github.com/browserslist/update-db#readme
124.6 Browserslist: caniuse-lite is outdated. Please run:
124.6   npx update-browserslist-db@latest
124.6   Why you should do it regularly: https://github.com/browserslist/update-db#readme
138.6  ERROR  Failed to compile with 18 errors10:16:02 AM
138.6
138.6  error  in ./plugins/charts/components/bar/BarChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/bar'
138.6
138.6  error  in ./plugins/charts/components/bar/BarChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/bar'
138.6
138.6  error  in ./plugins/charts/components/bubble/BubbleChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/bubble'
138.6
138.6  error  in ./plugins/charts/components/bubble/BubbleChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/bubble'
138.6
138.6  error  in ./plugins/charts/components/doughnut/DoughnutChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/doughnut'
138.6
138.6  error  in ./plugins/charts/components/doughnut/DoughnutChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/doughnut'
138.6
138.6  error  in ./plugins/charts/components/line/LineChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/line'
138.6
138.6  error  in ./plugins/charts/components/line/LineChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/line'
138.6
138.6  error  in ./plugins/charts/components/pie/PieChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/pie'
138.6
138.6  error  in ./plugins/charts/components/pie/PieChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/pie'
138.6
138.6  error  in ./plugins/charts/components/polararea/PolarArea.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/polararea'
138.6
138.6  error  in ./plugins/charts/components/polararea/PolarArea.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/polararea'
138.6
138.6  error  in ./plugins/charts/components/polararea/PolarArea.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'chartjs-color' in '/var/www/plugins/charts/components/polararea'
138.6
138.6  error  in ./plugins/charts/components/radar/RadarChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/radar'
138.6
138.6  error  in ./plugins/charts/components/radar/RadarChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/radar'
138.6
138.6  error  in ./plugins/charts/components/radar/RadarChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'chartjs-color' in '/var/www/plugins/charts/components/radar'
138.6
138.6  error  in ./plugins/charts/components/scatter/ScatterChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'vue-chartjs/legacy' in '/var/www/plugins/charts/components/scatter'
138.6
138.6  error  in ./plugins/charts/components/scatter/ScatterChart.vue?vue&type=script&lang=js&
138.6
138.6 Module not found: Error: Can't resolve 'chart.js' in '/var/www/plugins/charts/components/scatter'
138.6
138.6  ERROR  Error: Build failed with errors.
138.6 Error: Build failed with errors.
138.6     at /var/www/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
138.6     at /var/www/node_modules/webpack/lib/webpack.js:148:8
138.6     at /var/www/node_modules/webpack/lib/HookWebpackError.js:68:3
138.6     at Hook.eval [as callAsync] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
138.6     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/node_modules/tapable/lib/Hook.js:18:14)
138.6     at Cache.shutdown (/var/www/node_modules/webpack/lib/Cache.js:150:23)
138.6     at /var/www/node_modules/webpack/lib/Compiler.js:1228:15
138.6     at Hook.eval [as callAsync] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
138.6     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/node_modules/tapable/lib/Hook.js:18:14)
138.6     at Compiler.close (/var/www/node_modules/webpack/lib/Compiler.js:1221:23)
138.6     at /var/www/node_modules/webpack/lib/webpack.js:147:16
138.6     at finalCallback (/var/www/node_modules/webpack/lib/Compiler.js:441:32)
138.6     at /var/www/node_modules/webpack/lib/Compiler.js:458:13
138.6     at Hook.eval [as callAsync] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
138.6     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/node_modules/tapable/lib/Hook.js:18:14)
138.6     at onCompiled (/var/www/node_modules/webpack/lib/Compiler.js:456:21)
138.6     at /var/www/node_modules/webpack/lib/Compiler.js:1199:17
138.6     at Hook.eval [as callAsync] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
138.6     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/node_modules/tapable/lib/Hook.js:18:14)
138.6     at /var/www/node_modules/webpack/lib/Compiler.js:1195:33
138.6     at finalCallback (/var/www/node_modules/webpack/lib/Compilation.js:2789:11)
138.6     at /var/www/node_modules/webpack/lib/Compilation.js:3094:11
138.6     at Hook.eval [as callAsync] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
138.6     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/node_modules/tapable/lib/Hook.js:18:14)
138.6     at /var/www/node_modules/webpack/lib/Compilation.js:3087:38
138.6     at eval (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
138.6     at eval (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
138.6     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
138.9 npm notice
138.9 npm notice New minor version of npm available! 10.1.0 -> 10.2.3
138.9 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.3>
138.9 npm notice Run `npm install -g npm@10.2.3` to update!
138.9 npm notice
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```

**Comment by rpiontik** [comment]
Исправлено в v3.6.0
